name: Build docset
on:
  push:
    branches: [main]
jobs:
  build:
    env:
      PYTORCH_VERSION: "2.4.1"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout pytorch
        uses: actions/checkout@v4
        with:
          repository: pytorch/pytorch
          ref: v${{ env.PYTORCH_VERSION }}
          path: pytorch
      - name: Apply patches to pytorch repository
        working-directory: pytorch
        run: |
          git config user.name 'GitHub Actions'
          git config user.email '<>'
          for i in $(ls ../patches/*.patch); do
            git am "$i"
          done
      - name: Configure Python dependencies
        run: |
          mv pytorch/docs/requirements.txt .
          echo "torch==${{ env.PYTORCH_VERSION }}" >> requirements.txt
          echo "doc2dash==3.1.0" >> requirements.txt
          echo "numpy==1.26.4" >> requirements.txt
          cat requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install KaTeX
        run: npm install --global katex
      - name: Compile docset
        env:
          SPHINXOPTS: "-j auto -WT"
        run: |
          make -C pytorch/docs docset
          mkdir output
          mv pytorch/docs/PyTorch.docset output
      - name: Upload docset
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-docset
          path: output
          if-no-files-found: error
